### ISSUE TITLE
FM 3.0 Search widget will bring up entries, but does not navigate to them.

### ISSUE THREAD

**Issue by KeithJGw** [pjdohertygis/FireMappers#29]
FM 3.0 Search widget will bring up entries, but does not navigate to them.
Searching for a county, street or otherwise brings up results, but clicking on the result doesn't navigate to them.

![20220909_190630_FM3 0SearchFail](https://user-images.githubusercontent.com/66851958/189464865-ab5ab90e-8115-456a-8abd-8e7141dafb34.jpg)

**Comment by pjdohertygis** [comment]
@KeithJGw - nice catch, this wasn't properly configured. Can you test now and report back?

**Comment by KeithJGw** [comment]
9/10/2022 1400 Hrs Now search doesn't come up with anything when something is typed into it and it says no results found.

**Comment by pjdohertygis** [comment]
Ok I think I fixed again, but based on usability I think I'll use the built-in search tool that comes with the map component. However, this is just a temporary solution - see https://github.com/pjdohertygis/FireMappers/issues/32 for more details.
