### ISSUE TITLE
Full screen map element in mobile does not work as expected.

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/FireMappers#31]
I turned this off for now, but I wanted to make it so a mobile user could expand the map and hide the bar at the top (they complained). 

![image](https://user-images.githubusercontent.com/4256979/189497768-0e35fc7d-d85f-4378-ae9b-bca517d15584.png)

But when I do this, all it does is hide some tools and there is not way to get back to "not fullscreen".

**Comment by pjdohertygis** [comment]
Example 

![image](https://user-images.githubusercontent.com/4256979/189497814-88d9488f-ec71-41df-a52b-92d659f6b6ba.jpeg)

**Comment by avezina** [comment]
Resolved, I had not properly setup the Header.
