### ISSUE TITLE
FM 2.0 & other PIM VIIRS layer displays NOAA-20 but not Suomi NPP heat detections.

### ISSUE THREAD

**Issue by KeithJGw** [pjdohertygis/FireMappers#42]
This layer has VIIRS sensors on the NOAA/NASA Suomi NPP and NOAA-20 satellites:
https://napsg.maps.arcgis.com/home/item.html?id=dece90af1a0242dcbf0ca36d30276aa3
Edit to add Clarification; PIM 2.0, 3.0, & 3.0 Media only display NOAA-20 detections.
I noticed this a while ago after Suomi was offline due to operational issues earlier this year then returned.
I compared VIIRS detections on *ALL PIMs 2.0, 3.0, & 3.0 Media to the opened the layer from the Item Details page in a new map to verify, and can also see the missing detection in Admin 2.0. 
9/13/2022  I used the Dutch fire in Placer County to verify it again.
I have double checked this several times in the past, but didn't mention it.
![20220913_195035_kj](https://user-images.githubusercontent.com/66851958/190047880-d29821b8-161d-42ad-b92d-80dc010bb53f.jpg)
![20220913_195030_kj](https://user-images.githubusercontent.com/66851958/190047924-f2672bf6-0123-4d60-973b-bd9af6165df9.jpg)
![20220913_195111_kj](https://user-images.githubusercontent.com/66851958/190047954-5613e19a-1ea9-427b-a3fa-9aa61f9ccade.jpg)
![20220913_195123_kj](https://user-images.githubusercontent.com/66851958/190048011-28f6364a-e24b-42f6-afca-de7e09178dd1.jpg)

Admin map shows both.
![20220913_195712_kj](https://user-images.githubusercontent.com/66851958/190048500-fd1c32a7-068a-4ccd-b262-cd9d3b653f84.jpg)

**Comment by pjdohertygis** [comment]
@KeithJGw so to be clear - you are saying Suomi NPP does show up in 3.0 but not in 2.0? If so this might be a filter in 2.0 web map or maybe an update they made to the service that did not get picked up in 2.0. 

I'll keep this issue open but will focus on higher priority stuff for the short-term. Thanks for catching all this stuff.

**Comment by KeithJGw** [comment]
Edited / added for clarification: PIM 2.0, 3.0, & 3.0 Media only display NOAA-20 detections.
I compared VIIRS detections on *ALL PIMs 2.0, 3.0, & 3.0 Media to the opened the layer from the Item Details page in a new map to verify, and can also see the missing Suomi detections in Admin 2.0.
Agree not a high priority thus I didn't mention it previously. Although since I'm logging issues, figured it should be noted.

**Comment by pjdohertygis** [comment]
This is good stuff to not let slip through the cracks.

Do you see Suomi in this service from the Living Atlas? 
https://www.arcgis.com/home/item.html?id=dece90af1a0242dcbf0ca36d30276aa3

**Comment by KeithJGw** [comment]
Aye, that's the layer linked in first entry that I opened in a new map to look for the difference.
Had to adjust the time slider for it to show. I chose Dutch fire then as there wasn't a lot of detects so it was less confusing to verify. It didn't freeze or gag the map while loading, so I didn't mention it as I didn't want to bug the daylights out of anyone or Adam over it. And I wanted to see if when Suomi data resumed if it was still weird, which it is.
![20220914_185423_kj](https://user-images.githubusercontent.com/66851958/190294975-5cc66696-c7ca-41fc-b36a-5c22bc2c1ba3.jpg)

**Comment by pjdohertygis** [comment]
ok then we might just have to take the existing layer out and it back in. I'll wait until we decide on web map approach for 3.0.

**Comment by KeithJGw** [comment]
Looks like the same data. Item details for the one in our map has a NAPSG url vs Arcgis, but it's the same as far as I can tell.
Both have url ending in "dece90af1a0242dcbf0ca36d30276aa3".
![20220914_192906_kj](https://user-images.githubusercontent.com/66851958/190299352-6c79deb4-d449-4097-9de6-b43064950332.jpg)

NAPSG prefix url item details page rest url:
https://services9.arcgis.com/RHVPKKiFTONKtxq3/arcgis/rest/services/Satellite_VIIRS_Thermal_Hotspots_and_Fire_Activity/FeatureServer
![20220914_191523_kj](https://user-images.githubusercontent.com/66851958/190298326-7c8faf99-02c7-4a71-9214-64bc32cb34cd.jpg)
Arcgis url item details page rest url: https://services9.arcgis.com/RHVPKKiFTONKtxq3/arcgis/rest/services/Satellite_VIIRS_Thermal_Hotspots_and_Fire_Activity/FeatureServer
![20220914_191533_kj](https://user-images.githubusercontent.com/66851958/190298382-d4fd73f2-3b52-4796-a671-229d84b4c853.jpg)

I can remove this part of the url "napsg.maps." and hit enter and it goes to an item with same rest url & update dates & slightly different view counts. Both have "Feature Layer from Esri' & "Managed by esri_livefeeds2"

**Comment by pjdohertygis** [comment]
Copy - so if the Living Atlas feed is showing all
the points and our web maps are not, there must be a filter setup or the layer just needs to be taken out, saved, and added back in. We will get to this eventually I promise.

**Comment by pjdohertygis** [comment]
@KeithJGw from FM 3.1 web map https://napsg.maps.arcgis.com/apps/mapviewer/index.html?webmap=58f752056455490f8040a24cb7fdc536, let's try this. 

Current filter was set to satellite = 1. I'll remove that, don't recall why it is there. 
![image](https://github.com/pjdohertygis/FireMappers/assets/4256979/8d0e5687-be0d-4fcf-93eb-0625b2cb1161)

Please let me know if this fixes the problem.

**Comment by pjdohertygis** [comment]
Fixed, at least for 3.1. I don't plan on fixing in earlier versions of FM.
